# Generated by Django 4.1 on 2022-08-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecategory_alter_article_options_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', through='articles.ArticleCategory', to='articles.category'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='main',
            field=models.BooleanField(default=True, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.category', verbose_name='Раздел'),
        ),
    ]
