# Generated by Django 4.1 on 2022-08-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_category_articles_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
